Создал фон основной страницы и карточки
brotegor/first-project pull request #24
Opened 2023-01-26 16:55 UTC by brotegor

2023-01-26 16:57 UTC, brotegor commented
Почему Readme поменялось, я его вроде не трогал?

2023-01-26 16:59 UTC, ArseniyDuck commented
да это был дефолтный readme, который react добавляет. я его удалил

2023-01-26 17:01 UTC, ArseniyDuck commented
ой, в коммите действительно что-то странное с ним

2023-01-27 04:30 UTC, ArseniyDuck requested changes

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/index.tsx
> +            <ul className={s.concepts}>
не `ul>li`, а `div` используй. и для списка, и для элементов

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/index.tsx
> +            <img src={background} alt="wergwgesdewg" className={s.mainimage}/>
alt="background image"

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +.mainimage{
в `index.scss` есть класс `ibg` для адаптивных картинок. используй его, а если надо добавить к нему еще какие-то свойства, повешай на элемент еще один класс.

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +    position: absolute;
карточки не надо позиционировать. их надо сделать с помощью `flex` или `grid`.

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +    & .b {
если просто надо написать стили для вложенного элемента, & использовать не надо.

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +    &:hover .a {
назови классы не `a` и `b`, а `defaultText` и `hoverText`

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +    &:hover .b {
сделай один `&:hover { ... }` и внутри пиши стили для `defaultText` и `hoverText`

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +        display: none;
вытащи из [этого файла](https://github.com/ArseniyDuck/chess/blob/main/src/styles/mixins.scss) два миксина `visible-element` и `hidden-element` в папку `styles/` в файл `mixins.scss`.  беда в том, что `display: block;` и `display: none;` не анимируются, а эти миксины анимировать можно. чтобы использовать миксин, в стилях дописываешь `@include mixin-name();`, и стили из миксина по сути просто вставляются на это место.

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +.main{
`.className { ... }`. пробел ставь между классом и скобками

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/index.tsx
> +                    <span className={s.a}>Цель</span>
не `span`, а `h3` для первого и `p` для второго

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +    background-color: var(--teal);
пиши `backgorund`

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +        color: #000;
black

2023-01-27 04:30 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +        display: inline;
убери

2023-01-28 06:05 UTC, brotegor commented on src/pages/Main/styles.module.scss
> +    position: absolute;
работает же
а с flex картинка убегает
зачем чинить то, что работает?

2023-01-28 06:17 UTC, ArseniyDuck requested changes

2023-01-28 06:17 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +.leftConcept {
убри эти костыли. верхний margin задай у `.concepts`, а боковые отступы настрой с помощью flex

2023-01-28 06:17 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +            color: black;
почему это только при `:hover` появляется? сделай это свойство в обычном `.hoverText`. вообще  в `:hover` ты пишешь только то, что изменяется

2023-01-28 06:17 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
>          background-color: var(--super-light-teal);
стили для самого элемента всегда пишутся до стилей вложенных элементов

2023-01-28 06:17 UTC, ArseniyDuck commented on src/styles/variables.scss
> +    --hover: all 1s ease;
слишком долгий промежуток времени указал, по-моему. если нужен еще один `transition`, создай для него новую переменную

2023-01-28 06:17 UTC, ArseniyDuck commented on src/pages/Main/index.tsx
> +            <div className={s.concepts}>
вынеси это в отдельный компонент Concepts. В этой же папке создай папку с таким именем и в нее помести index.tsx и styles.module.scss. Оформи по аналогии с тем, что уже есть

2023-01-28 06:17 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +.leftConcept {
убери эти костыли. верхний отступ задай у самого контейнера, а боковые настрой с помощью flex

2023-01-28 06:17 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +            color: black;
в `:hover` пиши только то, что изменяется. это свойство должно быть у элемента и до наведения

2023-01-28 06:17 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
>          background-color: var(--super-light-teal);
стили самого элемента всегда пиши до стилей вложенных элементов

2023-01-28 06:17 UTC, ArseniyDuck commented on src/styles/mixins.scss
> +    display: none;
смысл этих миксинов в том, чтобы перестать использовать display. убери их отсюда

2023-01-28 06:18 UTC, ArseniyDuck commented on src/pages/Main/styles.module.scss
> +    position: absolute;
не убрал позиционирование

2023-01-28 06:19 UTC, ArseniyDuck commented
с прошлого ревью остались еще комменты, не всё сделал. сделанное я как resolved пометил

2023-01-28 07:58 UTC, merged